server:
  port: 8888
spring:
  datasource:
    druid:
      url:  jdbc:mysql://192.168.1.69:3306/school?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
      username: root
      #password: 123456
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 10
      min-idle:  1
      max-active:  50
      max-wait:  60000
swagger:
  base-package: com.ctbu.school.controller
  title: ctbu
  description: ??????
  authorization:
    key-name: Authorization